services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped

    ports:
        - "${MEALIE_PORT}:9000"

    volumes:
      - type: volume
        source: data
        target: /app/data/
        read_only: false
        volume:
          nocopy: true

    environment:
      - TZ=${TZ}
      - BASE_URL=http://${RASPBERRY_IP}:${MEALIE_PORT}
      - ALLOW_SIGNUP=true
      - DEFAULT_GROUP=Dom
      - DEFAULT_HOUSEHOLD=Rodzina

    mem_limit: 2048m

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  data: