services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped

    ports:
        - "9925:9000"

    volumes:
      - type: volume
        source: data
        target: /app/data/
        read_only: false
        volume:
          nocopy: true

    environment:
      - TZ=${TZ}
      - BASE_URL=http://${RASPBERRY_IP}:9925
      - ALLOW_SIGNUP=true
      - DEFAULT_GROUP=Dom
      - DEFAULT_HOUSEHOLD=Rodzina

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9925"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 1000M

volumes:
  data:
