services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always

    ports:
      - ${OWNCLOUD_PORT}:8080

    volumes:
      - type: bind
        source: /mnt/owncloud_disk
        target: /mnt/owncloud_disk
        read_only: false
        bind:
          create_host_path: true

    environment:
      - OWNCLOUD_VOLUME_FILES=/mnt/owncloud_disk
      - OWNCLOUD_DOMAIN=${RASPBERRY_IP}:${OWNCLOUD_PORT}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis

    depends_on:
      - mariadb
      - redis

    mem_limit: 2048m

    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - server_tier
      - database_tier
      - cache_tier

  mariadb:
    image: mariadb:10.11
    container_name: owncloud_mariadb
    restart: always

    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
        read_only: false
        volume:
          nocopy: true

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1

    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]

    mem_limit: 2048m

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - database_tier

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always

    volumes:
      - type: volume
        source: redis
        target: /data
        read_only: false
        volume:
          nocopy: true

    command: ["--databases", "1"]

    mem_limit: 2048m

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - cache_tier

volumes:
  mysql:
  redis:

networks:
  server_tier:
  database_tier:
  cache_tier: