services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - '9443:9443'
    volumes:
      - '~/docker/portainer/etc-portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
