services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9443:9443"

    volumes:
      - type: volume
        source: data
        target: /data
        read_only: false
        volume:
          nocopy: true

      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  data:

